### ISSUE TITLE
Issue: 'undefined method any?'

### ISSUE THREAD

**Issue by chamsters** [celsworth/octolux#2]
Hi there, me again :)

I can't figure this one out unfortunately...
I'm trying to make use of your smart octopus rules script. I have no idea if it's working based on the output in the log file:

```
rules.rb:73:in `<main>': **undefined method `any?' for nil:NilClass** (NoMethodError)
	from /octolux/octolux.rb:28:in `instance_eval'
	from /octolux/octolux.rb:28:in `<main>'
I, [2020-03-14T19:59:26.944449 #4404]  INFO -- : Current Price = 8.274p
I, [2020-03-14T19:59:26.948678 #4404]  INFO -- : SOC = 10% / 90%, charge_size = 3.84 kWh, hours = 1.54
rules.rb:73:in `<main>': undefined method `any?' for nil:NilClass (NoMethodError)
	from /octolux/octolux.rb:28:in `instance_eval'
	from /octolux/octolux.rb:28:in `<main>'
I, [2020-03-14T19:59:37.158243 #4409]  INFO -- : Current Price = 8.274p
I, [2020-03-14T19:59:37.170503 #4409]  INFO -- : SOC = 10% / 90%, charge_size = 3.84 kWh, hours = 1.54
```

Plus side is it is taking my SOC from the server, my charge size, hours correctly. Is there any way to 'see' what slots it has picked as cheapest times and when it would ultimately start grid charging? i.e. can I preempt / predict what it'll do or do I just need to keep fingers crossed and check the next day?

**Comment by celsworth** [comment]
I've just pushed up a completely new https://github.com/celsworth/octolux/blob/master/doc/rules.example.agile_cheap_slots.rb so pull down the changes and copy this to `rules.rb` again. Hopefully this will work better (it's the one I'm currently using).

It needs a couple of `config.ini` settings like so, if you didn't have them already:

```
[rules]
required_soc = 80
cheap_charge = 2
```

It will log output like this when it decides which slots to use, which is normally done at 9pm (assuming it has the latest prices by then)

```
I, [2020-03-14T20:00:03.899763 #2684]  INFO -- : Charge: 2020-03-15 03:00:00 UTC @ 1.9845p
I, [2020-03-14T20:00:03.899945 #2684]  INFO -- : Charge: 2020-03-15 03:30:00 UTC @ 0.882p
```

**Comment by azimhusain** [comment]
That's done it :)

`I, [2020-03-14T20:27:55.312454 #14011]  INFO -- : Current Price = 7.287p
I, [2020-03-14T20:27:55.315753 #14011]  INFO -- : SOC = 10% / 90%
I, [2020-03-14T20:27:55.320374 #14011]  INFO -- : charge_size = 3.84 kWh, hours = 1.92
I, [2020-03-14T20:27:55.322296 #14011]  INFO -- : Charge: 2020-03-15 01:30:00 UTC @ 1.89p
I, [2020-03-14T20:27:55.322314 #14011]  INFO -- : Charge: 2020-03-15 02:30:00 UTC @ 1.89p
I, [2020-03-14T20:27:55.322322 #14011]  INFO -- : Charge: 2020-03-15 03:00:00 UTC @ 1.89p
I, [2020-03-14T20:27:55.322329 #14011]  INFO -- : Charge: 2020-03-15 03:30:00 UTC @ 0.84p
I, [2020-03-14T20:27:55.322336 #14011]  INFO -- : Charge: 2020-03-15 04:00:00 UTC @ 1.89p
I, [2020-03-14T20:27:55.322342 #14011]  INFO -- : Charge: 2020-03-15 04:30:00 UTC @ 1.05p
I, [2020-03-14T20:27:55.322348 #14011]  INFO -- : Charge: 2020-03-15 05:00:00 UTC @ 1.05p
I, [2020-03-14T20:27:55.322365 #14011]  INFO -- : Charge: 2020-03-15 05:30:00 UTC @ 1.89p
I, [2020-03-14T20:27:55.325117 #14011]  INFO -- : Idle: 2020-03-14 23:30:00 UTC @ 2.94p
I, [2020-03-14T20:27:55.325131 #14011]  INFO -- : Idle: 2020-03-15 00:00:00 UTC @ 2.1p
I, [2020-03-14T20:27:55.325139 #14011]  INFO -- : Idle: 2020-03-15 02:00:00 UTC @ 2.52p
I, [2020-03-14T20:27:55.325146 #14011]  INFO -- : Idle: 2020-03-15 06:00:00 UTC @ 2.52p
I, [2020-03-14T20:27:55.325152 #14011]  INFO -- : Idle: 2020-03-15 06:30:00 UTC @ 2.73p
I, [2020-03-14T20:27:55.325158 #14011]  INFO -- : Idle: 2020-03-15 08:00:00 UTC @ 2.751p
I, [2020-03-14T20:27:55.325177 #14011]  INFO -- : ac_charge = false ; discharge = true (> 3.024p)
D, [2020-03-14T20:27:55.326745 #14011] DEBUG -- : set_register(65, 100)
D, [2020-03-14T20:27:56.127304 #14011] DEBUG -- : set_register(65) => 100
D, [2020-03-14T20:27:56.127337 #14011] DEBUG -- : charge(false)
D, [2020-03-14T20:27:56.127347 #14011] DEBUG -- : update_register(21, 128, false)
D, [2020-03-14T20:27:56.127354 #14011] DEBUG -- : read_register(21)
D, [2020-03-14T20:27:57.148295 #14011] DEBUG -- : read_register(21) => 61780
D, [2020-03-14T20:27:57.148328 #14011] DEBUG -- : update_register(21) => no action required`\


You clearly are comfy with Ruby - do you mind if I ask some likely silly questions (again, i come from PHP background - my first foray into Ruby!). 

1) I clearly am having some ruby issues. My server had an old version (2.0) which I updated to 2.6. If i type ruby --v I see ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]. But when I CD into /octlux I get a message "Unknown ruby interpreter version (do not know how to handle): >=2.3.0."

2) Can I run as root?? When running octolux.sh I get the very correct output above showing the perfect charge slots. But if I add 0,30 * * * * /octolux/octolux.sh to my crontab (root's one) I get:
`/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /octolux/boot.rb:8:in `<top (required)>'
	from /octolux/octolux.rb:4:in `require_relative'
	from /octolux/octolux.rb:4:in `<main>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /octolux/boot.rb:8:in `<top (required)>'
	from /octolux/octolux.rb:4:in `require_relative'
	from /octolux/octolux.rb:4:in `<main>'`

Which likely is related to conflicting ruby versions but I can't tell...

3) This may sound like a crazy scenario but I'd like to use more from the grid rather than battery when energy price is, say, <8p (I use loads of energy, don't want to deplete battery before peak periods!). is there an easy way to do this? With your old octopus file I could see there was a section that says don't use the battery if the average price of the charge was x amount less than current price - i was just going to hack that code up to hardcode it to say don't provide energy (i.e. go to sleep) if it's <8p. your new code is ... lot more complex :) Still going through it but if you do have an easy pointer that'd be amazing!

Again - thanks so much for this... I'm going through your code now :)

**Comment by celsworth** [comment]
For the first couple of points, how did you install the newer Ruby? Is it now the only Ruby version available? Might just be worth checking `/usr/bin`, `/usr/local/bin` etc, in case any older ones are still around and confusing things.

That `Unknown ruby interpreter version` usually crops up if you're using a Ruby package manager like rvm or rbenv, are you doing anything like that? As a bodge-fix you could try commenting out the line that says `ruby '>= 2.3.0'` in `Gemfile` but it shouldn't be necessary.. If running `ruby` in the `octolux` directory works, then you should be good to go from there.

To fix the `require': cannot load such file -- bundler/setup`, try `gem install bundler` (as root, most likely).

I'll have a look at the third point tomorrow, I think it'll be fairly easy to get something like that back in.. the new code tries to work out dynamically what price to go idle at, but that could be overridden with a value in config or something pretty easily.

**Comment by azimhusain** [comment]
Some progress...

I installed ruby using guidance here: https://tecadmin.net/install-ruby-latest-stable-centos/
I have found the 'old' ruby version in /usr/bin - i removed that. Nothing in /usr/local/bin. 
You are right - I have rvm - but error around rub > 2.3.0 disappeared once i commented oout the Gemfile entry, but probably doesn't solve the underlying issue!

I've installed bundler - I have 2.1.4. 

Still no issues at all running the shell script directly. But, trying to run via cron I see a whole essay of errors!

`/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:83:in `new'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:83:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:234:in `new'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:234:in `to_definition'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:13:in `evaluate'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:34:in `build'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler.rb:135:in `definition'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler.rb:101:in `setup'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /octolux/boot.rb:8:in `<top (required)>'
	from /octolux/octolux.rb:4:in `require_relative'
	from /octolux/octolux.rb:4:in `<main>'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (2.1.4) required by your /octolux/Gemfile.lock. (Gem::MissingSpecVersionError)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
Checked in 'GEM_PATH=/octolux/vendor/bundle/ruby/2.6.0', execute `gem env` for more information
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:42:in `require'
	from /octolux/boot.rb:8:in `<top (required)>'
	from /octolux/octolux.rb:4:in `require_relative'
	from /octolux/octolux.rb:4:in `<main>'`

**Comment by chamsters** [comment]
Got it to work!

Removed RVM, installed ruby from scratch. Had to tweak the sh wrapper as it wasn't finding ruby properly, but after specifying exact location it works great :)

batteries are now charging as they should be. Lets see how it looks tomorrow!

So just the third point left which I'll have a play with too, tomorrow. It's 2:45am and I could do with some sleep :)

**Comment by chamsters** [comment]
Hm... Would min_discharge_price = 8 do it?

My batts charged perfectly last night, but with my house base load of 2.5kw the batteries were dead by 8am as it min_discharge_price was just over 2.5p based on the formula there now...

**Comment by celsworth** [comment]
Nice, well done for getting it working! RVM isn't really necessary unless you specifically want to run multiple versions of Ruby at once. Just installing it natively is simpler usually.

So yes, the rules file you're using at the moment will discharge the batteries when the price rises above what you paid to charge it. All the multiplier stuff is an attempt to more and more selectively discharge depending on what the SOC is. This usually works out well enough for me as I have a low base load.

You can probably remove all that, and replace it all with `min_discharge_price = 8`. So everything from line 62:

```ruby
max_charge_price = charge_slots[charge_slots.keys.last] || cheap_charge
```

to line 73:

```ruby
min_discharge_price = (max_charge_price * multiplier).round(4)
```

Can all simply be replaced with setting `min_discharge_price` to a static number. Note that however the logic above that, which decides which slots to charge in, may still pick slots that are above 8p if the rate never drops below 8p overnight. So in that case you might charge at 8.5p overnight then discharge at 8p again the following morning - which would be a net loss.

To avoid that, you could do something like..

```ruby
min_discharge_price = [max_charge_price + 1, 8].max
```

So this will take the maximum price you charged at and add 1p - then also the static number 8, and find the maximum of those values. This will avoid discharging at prices lower than you paid to charge.

**Comment by celsworth** [comment]
If you're more comfortable in Python, what I am actually pondering doing is adding some API endpoints to the server that will enable/disable charge/discharge.

So you could then knock up anything in Python that you wanted and just do a HTTP call to this server to get the inverter doing what you wanted.

**Comment by celsworth** [comment]
I've actually added the above to the sample rules file: see https://github.com/celsworth/octolux/commit/b6ba54a175450aee1cd89970913d9e0425ea0e22

So now if you copy that rules file in, and add your preferred minimum-discharge price into config as shown in the commit, you should see:

```
I, [2020-03-15T12:41:59.776417 #8052]  INFO -- : Current Price = 7.7595p
I, [2020-03-15T12:41:59.785464 #8052]  INFO -- : SOC = 73% / 80%
I, [2020-03-15T12:41:59.843539 #8052]  INFO -- : Charge: 2020-03-15 03:30:00 UTC @ 0.882p
I, [2020-03-15T12:41:59.874130 #8052]  INFO -- : ac_charge = false ; discharge = true (> 3.0p)
```

ie, its using 3p as the minimum discharge, even though I only charged this morning at 0.8p.

**Comment by chamsters** [comment]
> Nice, well done for getting it working! RVM isn't really necessary unless you specifically want to run multiple versions of Ruby at once. Just installing it natively is simpler usually.
> 
> So yes, the rules file you're using at the moment will discharge the batteries when the price rises above what you paid to charge it. All the multiplier stuff is an attempt to more and more selectively discharge depending on what the SOC is. This usually works out well enough for me as I have a low base load.
> 
> You can probably remove all that, and replace it all with `min_discharge_price = 8`. So everything in lines 62-73:
> 
> ```ruby
> max_charge_price = charge_slots[charge_slots.keys.last] || cheap_charge
> # discharge_slots depends how much SOC we have. The more SOC, we more generous we can be
> # with discharging. The lower the SOC, the more we want to save that charge for higher prices.
> multiplier = if soc < 30 then 1.6
>              elsif soc < 40 then 1.5
>              elsif soc < 50 then 1.4
>              elsif soc < 60 then 1.3
>              elsif soc < 80 then 1.2
>              else
>                1.1
>              end
> min_discharge_price = (max_charge_price * multiplier).round(4)
> ```
> 
> Can all simply be replaced with setting `min_discharge_price` to a static number. Note that however the logic above that, which decides which slots to charge in, may still pick slots that are above 8p if the rate never drops below 8p overnight. So in that case you might charge at 8.5p overnight then discharge at 8p again the following morning - which would be a net loss.
> 
> To avoid that, you could do something like..
> 
> ```ruby
> max_charge_price = charge_slots[charge_slots.keys.last] || cheap_charge
> min_discharge_price = [max_charge_price + 1, 8].max
> ```
> 
> So this will take the maximum price you charged at and add 1p - then also the static number 8, and find the maximum of those values. This will avoid discharging at prices lower than you paid to charge.

Ah, that's a good point around charging at 8.5 and losing on 8.5 - good thinking!

**Comment by chamsters** [comment]
> If you're more comfortable in Python, what I am actually pondering doing is adding some API endpoints to the server that will enable/disable charge/discharge.
> 
> So you could then knock up anything in Python that you wanted and just do a HTTP call to this server to get the inverter doing what you wanted.

This would be a huge win - would love to see this in the roadmap :)

**Comment by chamsters** [comment]
> I've actually added the above to the sample rules file: see [b6ba54a](https://github.com/celsworth/octolux/commit/b6ba54a175450aee1cd89970913d9e0425ea0e22)
> 
> So now if you copy that rules file in, and add your preferred minimum-discharge price into config as shown in the commit, you should see:
> 
> ```
> I, [2020-03-15T12:41:59.776417 #8052]  INFO -- : Current Price = 7.7595p
> I, [2020-03-15T12:41:59.785464 #8052]  INFO -- : SOC = 73% / 80%
> I, [2020-03-15T12:41:59.843539 #8052]  INFO -- : Charge: 2020-03-15 03:30:00 UTC @ 0.882p
> I, [2020-03-15T12:41:59.874130 #8052]  INFO -- : ac_charge = false ; discharge = true (> 3.0p)
> ```
> 
> ie, its using 3p as the minimum discharge, even though I only charged this morning at 0.8p.
> 
> All that stuff about the multiplier I left in for now but it might be more complication than it's worth. Still experimenting really to find the best things that work!
> 
> And whoops, looks like I missed adding the `cheap_charge` to the sample config previously.

Magic! Incorporated that in, let's see how the next 24 hours look... Thanks again!

**Comment by chamsters** [comment]
I've done some pretty piss poor coding to add a scenario below. Basically, it says if the octopus price is over what i've defined in the config file (in my case, 15p/kwh) then uncap the discharge rate. Any other times of day, assuming the minimum rate (in my case 8p - based on this thread above) then only provide 33% (i.e. 1000 watts) max, just to make sure I have enough left over for later in the day. I may lower this 33% further - but will test for a few days.


`full_power = CONFIG['rules']['full_power']
if octopus.price >= full_power
  dischargetarget = 100
  LOGGER.info "Octopus Price over target price of #{full_power}, setting discharge cap to 100%"
else
  dischargetarget = 33
  LOGGER.info "Octopus price below target price of #{full_power}, setting discharge cap to 33%"
end

discharge_pct = discharge ? dischargetarget : 0`
